CREATE USER SHORTS_DB IDENTIFIED BY shorts1234;

GRANT CREATE SESSION TO SHORTS_DB;
GRANT CREATE TABLE TO SHORTS_DB;
GRANT CREATE SEQUENCE TO SHORTS_DB;

ALTER USER SHORTS_DB QUOTA UNLIMITED ON USERS;